/*
This is an auto-generated file.
Do not edit this file directly, instead use the SiegeTrain tool.
https://github.com/sleepyparadox/SiegeTrain
```json
{
	"Class": "Releases",
	"Format": "cs",
	"Namespace": "SiegeTower.Api",
	"LatestOnly": true
}
```
*/
namespace SiegeTower.Api;
using System.Collections.Frozen;

public static class Releases
{
	public static Release Current => V0_2_0;
	public static readonly Release V0_2_0 = new("0.2.0", 0, 2, 0);
}
public class Release
{
	public string Version { get; }
	public uint MajorVersion { get; }
	public uint MinorVersion { get; }
	public uint PatchVersion { get; }

	public Release(string version, uint majorVersion, uint minorVersion, uint patchVersion)
	{
		Version = version;
		MajorVersion = majorVersion;
		MinorVersion = minorVersion;
		PatchVersion = patchVersion;
	}
}
